browser = firefox
url = https://naveenautomationlabs.com/opencart/index.php?route=account/login 

headless = false
incognito = false 

username = bimala@nasa.com
password = Automation123$

remote = true
